services:
  java_app_clientes_ms:
    container_name: java_app_clientes_ms
    image: clientes-ms-java-app:1.0.0
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_server_clientes_ms:5432/clientes_ms_db
      - DATABASE_USERNAME=elias
      - DATABASE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=localhost
    depends_on:
      - postgres_server_clientes_ms
    networks:
      - micro_net

  postgres_server_clientes_ms:
    container_name: postgres_server_clientes_ms
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: elias
      POSTGRES_DB: clientes_ms_db
      POSTGRES_PASSWORD: root
    volumes:
      - database_vol_clientes_ms:/var/lib/postgresql/data
    networks:
      - micro_net

  pgadmin_clientes_ms:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    depends_on:
      - postgres_server_clientes_ms
    networks:
      - micro_net

volumes:
  database_vol_clientes_ms:

networks:
  micro_net:
    external: true
